// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/main/aside/index.vue')['default']
    Canvas: typeof import('./src/components/lowcode/canvas/index.vue')['default']
    ComponentRenderer: typeof import('./src/components/lowcode/canvas/component-renderer/component-renderer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Form: typeof import('./src/components/lowcode/form/index.vue')['default']
    Header: typeof import('./src/components/main/header/index.vue')['default']
    LeftSource: typeof import('./src/components/lowcode/left-source/index.vue')['default']
    Lowcode: typeof import('./src/components/lowcode/index.vue')['default']
    Main: typeof import('./src/components/main/main/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SizeController: typeof import('./src/components/lowcode/canvas/size-controller/index.vue')['default']
  }
}
